### ISSUE TITLE
Support for custom implementation of Serialize trait

### ISSUE THREAD

**Issue by HHogg** [1Password/typeshare#110]
With something along the lines of the below where an enum (or anything serializable) that has a custom implementation of Serialize, it would be helpful to the type that is serialized. 

**With**

```rs
#[typeshare]
pub enum Thing {
  Foo {
    a: String,
  },
  Bar { 
    a: String,
    b: String,
  }
}

impl ToString for Thing {
  fn to_string(&self) -> String {
    match self {
      Self::Foo { a } => format!("F({})", a),
      Self::Bar { a, b } => format!("B({}, {})", a, b),
    }
  }
}

impl Serialize for Thing {
  fn serialize<S: Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
    serializer.serialize_str(&self.to_string())
  }
}
```

**Currently**

It errors with 

```
thread '<unnamed>' panicked at 'serde tag attribute needs to be specified for algebraic enum Thing. e.g. #[serde(tag = "type", content = "content")]'
```

**Desired**

```ts
export type Thing = string;
```

**Comment by CerulanLumina** [comment]
Hello, thanks for submitting an issue! Currently, we parse the serde tags to determine how the types should be identified, and as a result this issue is difficult to resolve, and therefore not a priority for us at 1Password. We welcome community contributions, however, and will keep this in mind should we decide on a major version bump.

**Comment by HHogg** [comment]
I'm happy to close this and use the macro `#[typeshare(serialized_as = "string")]`
