### ISSUE TITLE
Typeshare ignores type annotations in embedded modules

### ISSUE THREAD

**Issue by d4h0** [1Password/typeshare#40]
Hi,

I have code like this:

```rust
mod my_module {
    // Types with Typeshare annotations
}
```

...which results in nothing being generated.

If I remove the module around the annotations, everything works.

**Comment by InquisitivePenguin** [comment]
This is probably an issue with our token visitor. I will look into this.

**Comment by InquisitivePenguin** [comment]
So there's two different issues here... one is that type annotations are silently ignored if they're in an inline module, while the other is that Typeshare doesn't support namespacing.

@Zonnex I'm going to break your problem into a new issue since that's a more complicated problem that intersects with similar design choices we're trying to decide on.
