### ISSUE TITLE
Making readonly properties in TypeScript 

### ISSUE THREAD

**Issue by Czocher** [1Password/typeshare#50]
Hello,
Is there any possibility to make force a generated TypeScript interface to have a readonly modifier on a property?

**Comment by InquisitivePenguin** [comment]
Not currently, but we can look into this!

**Comment by Czocher** [comment]
Thanks @InquisitivePenguin! If I can help in any way feel free to mention me ;).

I can imagine a general solution where fields can be annotated with e.g. `#[typeshare(prepend_typescript_with="readonly")]`, the value of the `prepend_typescript_with` property would be then copied as-is to the result.

A far better solution would be to provide a map of a language name to some string value, so that a user could define this for every language separately.

Alternatively adding a `#[typeshare(readonly=true)] ` property which would try to generate a readonly property for every language on a best-effort basis may be an even better solution.

What do you think?

**Comment by InquisitivePenguin** [comment]
Sorry for the late response @Czocher. I would definitely support merging this!

As for the syntax - what would you think about `#[typeshare(typescript(readonly))]`? For language-specific features like this one, the precedent has been to scope them within the language name. Now, currently, we use this for language specific-names, like `#[typeshare(kotlin = "myKtFunction", swift = "mySwiftFunction")]`, and I think it would make sense to do something similar with boolean values, using the idiom of just including the field name instead of setting it to `true` manually, since it will be false by default.

**Comment by Czocher** [comment]
Thanks for your response @InquisitivePenguin. LGTM, I'll have a look how to implement the `#typeshare(typescript(readonly))` version :)

**Comment by InquisitivePenguin** [comment]
Thank you! Let me know if you have any questions or roadblocks you run into.
